### ISSUE TITLE
No way to set encryption key/password?

### ISSUE THREAD

**Issue by accaldwell** [emersion/bups#17] opened 2016-05-06 01:01 UTC
When making a backup with "Encrypt filesystem" checked, there is apparently no way to set a password or encryption key. Yet, the backup completes fine and can be mounted (again, with no password).

Is something not implemented or is it just encrypting with an empty key?

**Comment by emersion** [comment] 2016-06-19 15:47
Strange. Can you run the app from a console to see the output? Normally a window asking you a password should appear.

**Comment by accaldwell** [comment] 2016-06-20 18:13
The relevant bits:

>Mounting filesystem...
/bin/sh: /usr/lib/ssh/ssh-askpass: No such file or directory
Initializing bup...
Reinitialized existing Git repository in /tmp/bups-encfs-dIzqp8/

Presumably the problem is there on line 2. So, two issues here:

1) bups is silently failing (at least in the GUI) to require a password when ssh-askpass is not available. The files are presumably being encrypted with no password.

2) Arch Linux is not listing whatever package ssh-askpass is provided by as a dependency. Emersion, you appear to be the Arch maintainer, so if you can confirm this, you should be able to push a fix to AUR.

**Comment by emersion** [comment] 2016-06-20 18:27
1. The problem is that I'm calling `encfs` and it doesn't returns any error. I will check for `ssh-askpass` before that.
2. Not sure if `ssh-askpass` should be listed as a dependency. I listed `encfs` as an optional dep, so I think `ssh-askpass` should be the same?

**Comment by emersion** [comment] 2016-06-20 18:41
1. is now fixed.

**Comment by accaldwell** [comment] 2016-06-20 19:04
Making it an optional dep makes sense, but since you are the main programmer and the Arch maintainer, I'll leave it to your discretion. 

The way you are hardcoding the path it seems to suggest it will only work with x11-ssh-askpass, and not one of the alternatives like openssh-askpass or lxqt-openssh-askpass. Not sure if there is a clever way to work around that.

**Comment by emersion** [comment] 2016-06-20 19:22
I've just updated the AUR package. I've opened another issue for the hardcoded askpass path: #20.

**Closed by emersion** 2016-06-20 19:22 UTC
Labels: bug
